[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && python manage.py create_admin && gunicorn sweet60_project.wsgi --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
