# Generated by Django 6.0.3 on 2026-04-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElderlyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อจริง')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('age', models.IntegerField(verbose_name='อายุ')),
                ('skills', models.TextField(verbose_name='ทักษะ/ความสามารถ')),
                ('experience', models.TextField(verbose_name='ประสบการณ์ทำงานที่ผ่านมา')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('company_name', models.CharField(max_length=200, verbose_name='ชื่อบริษัท/ร้านค้า')),
                ('description', models.TextField(verbose_name='รายละเอียดงาน')),
                ('salary', models.CharField(max_length=100, verbose_name='เงินเดือน/ค่าจ้าง')),
                ('is_active', models.BooleanField(default=True, verbose_name='ยังเปิดรับสมัครอยู่ไหม')),
            ],
        ),
    ]
