# Generated by Django 6.0.3 on 2026-04-23 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('experience', models.TextField(blank=True, verbose_name='ประสบการณ์ทำงาน')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='รูปบัตรประชาชน')),
                ('no_criminal_record', models.BooleanField(default=False, verbose_name='ยืนยันไม่มีประวัติอาชญากรรม')),
                ('consent_id_upload', models.BooleanField(default=False, verbose_name='ยินยอมอัปโหลดบัตร')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
