# Generated by Django 6.0.3 on 2026-04-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0006_remove_communitypost_author_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อกลุ่ม')),
                ('category', models.CharField(blank=True, choices=[('fitness', 'สุขภาพและฟิตเนส'), ('arts', 'ศิลปะและงานฝีมือ'), ('travel', 'ท่องเที่ยวและกิจกรรมกลางแจ้ง'), ('tech', 'เทคโนโลยีและการเรียนรู้'), ('social', 'พบปะสังสรรค์')], max_length=50, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='รูปภาพกลุ่ม')),
                ('is_private', models.BooleanField(default=False, verbose_name='กลุ่มส่วนตัว')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='สถานที่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
