# Generated by Django 6.0.3 on 2026-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0009_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_b64',
            field=models.TextField(blank=True, default='', verbose_name='รูปโปรไฟล์'),
        ),
    ]
