# Generated by Django 5.2.13 on 2026-04-26 17:11

from django.conf import settings
from django.db import migrations, models

def fix_zero_salary(apps, schema_editor):
    """Set any salary <= 0 to 1 before adding PositiveIntegerField constraint."""
    JobListing = apps.get_model('jobs_app', 'JobListing')
    JobListing.objects.filter(salary__lte=0).update(salary=1)

class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0011_convert_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Fix data First, before adding the PositiveIntegerField constraint
        migrations.RunPython(fix_zero_salary, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='เงินเดือน/ค่าจ้าง'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
