# Generated by Django 5.2.13 on 2026-04-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0013_fix_zero_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(default='พาร์ทไทม์', max_length=100, verbose_name='ประเภทงาน'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='คุณสมบัติที่ต้องการ'),
        ),
    ]
