# Generated by Django 5.2.13 on 2026-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0014_joblisting_job_type_joblisting_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='cover_image_b64',
            field=models.TextField(blank=True, default='', verbose_name='รูปภาพกลุ่ม (Base64)'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='ประเภทงาน'),
        ),
    ]
